services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'sjames-au/brakeman']
    volumes:
      - ".:/plugin:ro"
  test:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
