#!/bin/bash

# Check if Brakeman is installed
if ! [ -x "$(command -v brakeman)" ]; then
  echo 'Error: Brakeman is not installed.' >&2
  exit 1
fi

# Run Brakeman and save the output to a file
brakeman -f json >brakeman_output.json

# Use the Buildkite agent to post the results
buildkite-agent annotate --context "brakeman" --style "info" --path "brakeman_output.json"
